spring:
  application:
    name: simple-ui

server:
  port: 8082
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      turbineCluster: pipa
    
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
      
#ribbon config
user-service.ribbon.ConnectTimeout: 5000
user-service.ribbon.ReadTimeout: 10000