spring:
  application:
    name: @project.name@
    
  redis:
    host: localhost
    port: 6379
    password: 123456

info.version: @project.version@

debug: true
log.level.ROOT: DEBUG

server:
  port: 8082
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      turbineCluster: pipa
    
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
      
#ribbon config
zuul-gateway.ribbon.ConnectTimeout: 5000
zuul-gateway.ribbon.ReadTimeout: 10000

# 默认是THREAD，表示hystrix command（包括Fignclient的方法）是在一个独立线程中执行，但是这样一来Feignclient的RequestInterceptor里面就取不到当前的Request对象，
# 为了在各微服务间传递sessionId，暂时先设置成SEMAPHORE，表示方法在当前线程中执行，可能影响效率，后续再找更优方案
hystrix.command.default.execution.isolation.strategy: SEMAPHORE